### ISSUE TITLE
Is any Salesforce data stored locally?

### ISSUE THREAD

**Issue by jdq22** [jereze/alfred-salesforce#6]
It looks like every search is issuing an API call, so no Salesforce data is stored locally. Is that right?

**Comment by jereze** [comment]
Hi Jenna,

Each search triggers an API call to Salesforce.com. No data is stored or cached locally. The workflow only keeps the OAuth access and refresh token.

I also clarify that the workflow runs entirely locally. Salesforce data is not shared with a third party.

**Comment by jdq22** [comment]
Thank you!! @jereze
